version: '3'

networks:
  front:
    external:
      name: front

volumes:
  croque-data:

services:

  croque:
    build: .
    restart: unless-stopped
    networks:
      - front
      - default
    volumes:
      - croque-data:/data/db
    environment:
      - NODE_ENV
      - CROQUE_SALT
      - CROQUE_MAIL_FROM
      - CROQUE_MAIL_HOST
      - CROQUE_MAIL_PORT
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:croque.epfl.life
      - traefik.port=9000
      - traefik.docker.network=front
