version: '3'

networks:
  front:
    external:
      name: front

volumes:
  croque-data:

services:

  croque:
    build: .
    restart: unless-stopped
    networks:
      - front
      - default
    volumes:
      - croque-data:/data/db
    environment:
      - NODE_ENV
      - CROQUE_SECRET
      - CROQUE_MAIL_REPLY_TO
      - CROQUE_MAIL_FROM
      - CROQUE_MAIL_HOST
      - CROQUE_MAIL_PORT
      - CROQUE_RAVEN
      - CROQUE_URL
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:croque.agepoly.ch,croque.epfl.ch
      - traefik.frontend.redirect.regex=https://croque.agepoly.ch
      - traefik.frontend.redirect.replacement=https://croque.epfl.ch
      - traefik.port=9000
      - traefik.docker.network=front
